services:
  wp-db:
    image: "postgres"
    container_name: "web_lab"
    environment:
      - POSTGRES_USER=marto
      - POSTGRES_PASSWORD=marto123
      - POSTGRES_DB=music
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
